[build]
  functions = "netlify/functions"

[functions]
  # Global settings, if needed

[functions.getUsers]
  timeout = 45

[[redirects]]
  from = "/"
  to = "/.netlify/functions/getUsers"
  status = 200
